apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base

images:
- name: ghcr.io/demo-org-np-migration/fraud-scoring
  newName: ghcr.io/demo-org-np-migration/fraud-scoring
  newTag: sha-e0963db

configMapGenerator:
- behavior: merge
  envs:
  - config.yaml
  name: fraud-scoring-config
