apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: ghcr.io/demo-org-np-migration/fraud-scoring
    newTag: latest

configMapGenerator:
  - name: fraud-scoring-config
    behavior: merge
    envs:
      - config.yaml
